### ISSUE TITLE
token export

### ISSUE THREAD

**Issue by maletazul** [felixge/node-dateformat#173]
Any reason to have this error in version 5

/home/luissilva/pool/node_modules/dateformat/lib/dateformat.js:26
export default function dateFormat (date, mask, utc, gmt) {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/luissilva/pool/lib/logger.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)

**Comment by mmunchandersen** [comment]
@maletazul did you solve the issue?
I'm getting "Uncaught SyntaxError: Unexpected token 'export' (at dateformat.js:1:283)" when simply importing dateformat.js in a cshtml page: "<script src="~/Scripts/dateformat.js"></script>"

**Comment by Celtics33** [comment]
Was this ever fixed ? 5.0.3 has "unexpected token 'export' error compared to 3.0.3 which just works
