### ISSUE TITLE
Not able to install dateFormat - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rjayaswal** [felixge/node-dateformat#64]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'dateFormat',
1 verbose cli   '--save' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData dateFormat
8 silly fetchNamedPackageData dateFormat
9 silly mapToRegistry name dateFormat
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'dateFormat',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'dateFormat',
12 silly mapToRegistry   name: 'dateFormat',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/dateFormat
14 verbose request uri https://registry.npmjs.org/dateFormat
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:05:55 PM
17 verbose request id f78e4ab09abb4f13
18 verbose etag W/"57d11e71-189"
19 verbose lastModified Thu, 08 Sep 2016 08:16:49 GMT
20 http request GET https://registry.npmjs.org/dateFormat
21 http 304 https://registry.npmjs.org/dateFormat
22 verbose headers { date: 'Tue, 02 May 2017 16:35:56 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"57d11e71-189"',
22 verbose headers   age: '147',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sin18025-SIN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1493742957.830855,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 02 May 2017 16:35:56 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"57d11e71-189"',
23 silly get     age: '147',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin18025-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1493742957.830855,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/dateFormat from cache
25 verbose get saving dateFormat to /home/rajayasw/.npm/registry.npmjs.org/dateFormat/.cache.json
26 verbose correctMkdir /home/rajayasw/.npm correctMkdir not in flight; initializing
27 verbose stack TypeError: Cannot convert undefined or null to object
27 verbose stack     at Function.keys (<anonymous>)
27 verbose stack     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:126:29)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
27 verbose stack     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
27 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
27 verbose stack     at FSReqWrap.oncomplete (fs.js:114:15)
28 verbose cwd /mnt/d/mongo-twitter
29 error Linux 4.4.0-43-Microsoft
30 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "dateFormat" "--save"
31 error node v7.9.0
32 error npm  v4.2.0
33 error Cannot convert undefined or null to object
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by jonschlinkert** [comment]
delete `node_modules`, then re-install

**Comment by chase-manning** [comment]
Closing due to inactivity and inability to replicate
